import {
  Category,
  DocumentItem,
  FaqItem,
  GlossaryItem,
  GroupItem,
  RoleItem,
  UserItem,
} from "./types";

export const categories: Category[] = [
  { id: "cat-hr", name: "人事", level: 1, order: 1 },
  { id: "cat-hr-rules", name: "規程", parentId: "cat-hr", level: 2, order: 1 },
  {
    id: "cat-hr-work",
    name: "就業規則",
    parentId: "cat-hr-rules",
    level: 3,
    order: 1,
  },
  { id: "cat-service", name: "服務", level: 1, order: 2 },
  { id: "cat-service-fulltime", name: "正社員", parentId: "cat-service", level: 2, order: 1 },
  { id: "cat-service-contract", name: "契約社員", parentId: "cat-service", level: 2, order: 2 },
  { id: "cat-service-rules", name: "服務規律", parentId: "cat-service", level: 2, order: 3 },
  { id: "cat-service-attitude", name: "勤務態度", parentId: "cat-service", level: 2, order: 4 },
  { id: "cat-service-sidejob", name: "副業", parentId: "cat-service", level: 2, order: 5 },
  { id: "cat-service-dualjob", name: "兼業", parentId: "cat-service", level: 2, order: 6 },
  { id: "cat-service-late", name: "遅刻・早退", parentId: "cat-service", level: 2, order: 7 },
  { id: "cat-service-violation", name: "服務違反", parentId: "cat-service", level: 2, order: 8 },
  { id: "cat-ga", name: "総務", level: 1, order: 3 },
  { id: "cat-acc", name: "経理", level: 1, order: 4 },
];

export const categoryNames = [
  "人事",
  "人事 / 規程",
  "人事 / 規程 / 就業規則",
  "服務",
  "服務 / 正社員",
  "服務 / 契約社員",
  "服務 / 服務規律",
  "服務 / 勤務態度",
  "服務 / 副業",
  "服務 / 兼業",
  "服務 / 遅刻・早退",
  "服務 / 服務違反",
  "総務",
  "経理",
];

export const documents: DocumentItem[] = [
  {
    id: "doc-001",
    displayName: "服務規程",
    version: "Ver.1.2",
    category: "人事 / 規程",
    registrationStatus: "レビュー中",
    syncStatus: "未同期",
    uploadFileName: "服務規程_20260401_r5.pdf",
    storagePath: "s3://qai-documents/policy-operations/regulation/po_reg_01.pdf",
    updatedAt: "2026/06/01",
  },
  {
    id: "doc-002",
    displayName: "経費精算マニュアル",
    version: "Ver.2.0",
    category: "経理",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "expense_manual_20260510.pdf",
    storagePath: "s3://qai-documents/accounting/expense_manual.pdf",
    updatedAt: "2026/05/10",
  },
  {
    id: "doc-003",
    displayName: "服務規律ガイド",
    version: "Ver.1.0",
    category: "服務 / 服務規律",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "service_rules_guide_20260601.pdf",
    storagePath: "s3://qai-documents/service/rules/service_rules_guide.pdf",
    updatedAt: "2026/06/03",
  },
  {
    id: "doc-004",
    displayName: "正社員服務ハンドブック",
    version: "Ver.1.1",
    category: "服務 / 正社員",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "fulltime_service_handbook_20260601.pdf",
    storagePath: "s3://qai-documents/service/fulltime/handbook.pdf",
    updatedAt: "2026/06/04",
  },
  {
    id: "doc-005",
    displayName: "副業・兼業ガイドライン",
    version: "Ver.1.0",
    category: "服務 / 副業",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "sidejob_guideline_20260601.pdf",
    storagePath: "s3://qai-documents/service/sidejob/guideline.pdf",
    updatedAt: "2026/06/07",
  },
  {
    id: "doc-006",
    displayName: "遅刻・早退時の服務取扱い",
    version: "Ver.1.0",
    category: "服務 / 遅刻・早退",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "late_early_leave_rules_20260601.pdf",
    storagePath: "s3://qai-documents/service/attendance/late_early_leave.pdf",
    updatedAt: "2026/06/07",
  },
  {
    id: "doc-007",
    displayName: "服務違反対応マニュアル",
    version: "Ver.1.0",
    category: "服務 / 服務違反",
    registrationStatus: "公開中",
    syncStatus: "同期済",
    uploadFileName: "service_violation_manual_20260601.pdf",
    storagePath: "s3://qai-documents/service/violation/manual.pdf",
    updatedAt: "2026/06/07",
  },
];

export const faqs: FaqItem[] = [
  {
    id: "faq-001",
    displayName: "有給休暇の申請方法",
    body: "勤怠システムから申請し、上長承認後に確定します。",
    featured: true,
    category: "人事 / 規程",
    updatedAt: "2026/06/02",
  },
  {
    id: "faq-002",
    displayName: "領収書の提出期限",
    body: "原則として精算月の翌月5営業日以内です。",
    featured: false,
    category: "経理",
    updatedAt: "2026/05/20",
  },
  {
    id: "faq-003",
    displayName: "服務規律違反時の確認先",
    body: "服務規律に関する確認は、所属長または人事労務担当へ相談してください。",
    featured: true,
    category: "服務 / 服務規律",
    updatedAt: "2026/06/05",
  },
  {
    id: "faq-004",
    displayName: "契約社員の服務ルール",
    body: "契約社員の服務ルールは雇用契約と服務規律に基づきます。",
    featured: false,
    category: "服務 / 契約社員",
    updatedAt: "2026/06/06",
  },
  {
    id: "faq-005",
    displayName: "副業はできますか",
    body: "副業は事前申請と会社承認が必要です。競業や勤務に支障が出る場合は認められないことがあります。",
    featured: true,
    category: "服務 / 副業",
    updatedAt: "2026/06/07",
  },
  {
    id: "faq-006",
    displayName: "遅刻した場合の扱い",
    body: "遅刻時は速やかに上長へ連絡し、勤怠システムで理由を申請してください。頻度や理由により指導対象となる場合があります。",
    featured: true,
    category: "服務 / 遅刻・早退",
    updatedAt: "2026/06/07",
  },
  {
    id: "faq-007",
    displayName: "服務違反になる行為",
    body: "無断欠勤、情報持ち出し、ハラスメント、勤務時間中の私用行為などは服務違反に該当する可能性があります。",
    featured: true,
    category: "服務 / 服務違反",
    updatedAt: "2026/06/07",
  },
];

export const glossaries: GlossaryItem[] = [
  {
    id: "gls-001",
    term: "ベクトルDB",
    meaning: "文章を検索しやすい数値表現に変換して保存するデータベースです。",
    updatedAt: "2026/06/01",
  },
  {
    id: "gls-002",
    term: "RAG",
    meaning: "検索した社内文書をもとにAIが回答する仕組みです。",
    updatedAt: "2026/05/29",
  },
];

export const roles: RoleItem[] = [
  {
    id: "role-user",
    displayName: "利用者",
    chatUsage: true,
    categoryManagement: false,
    documentManagement: false,
    faqManagement: false,
    glossaryManagement: false,
    userManagement: false,
    groupManagement: false,
    roleManagement: false,
  },
  {
    id: "role-editor",
    displayName: "編集者",
    chatUsage: true,
    categoryManagement: true,
    documentManagement: true,
    faqManagement: true,
    glossaryManagement: true,
    userManagement: false,
    groupManagement: false,
    roleManagement: false,
  },
  {
    id: "role-admin",
    displayName: "管理者",
    chatUsage: true,
    categoryManagement: true,
    documentManagement: true,
    faqManagement: true,
    glossaryManagement: true,
    userManagement: true,
    groupManagement: true,
    roleManagement: true,
  },
];

export const groups: GroupItem[] = [
  {
    id: "group-hr",
    displayName: "人事部",
    categories: ["人事", "服務"],
    memberCount: 12,
  },
  {
    id: "group-backoffice",
    displayName: "管理部",
    categories: ["人事", "人事 / 規程", "服務", "経理"],
    memberCount: 24,
  },
];

export const users: UserItem[] = [
  {
    id: "user-001",
    displayName: "山田 太郎",
    email: "taro.yamada@example.com",
    groups: ["人事部"],
    role: "編集者",
  },
  {
    id: "user-002",
    displayName: "佐藤 花子",
    email: "hanako.sato@example.com",
    groups: ["管理部", "人事部"],
    role: "管理者",
  },
];
